name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run container as staging
        run: |
          docker stop hello-node-staging || true
          docker rm hello-node-staging || true
          docker run -d -p 8080:8080 --name hello-node-staging hello-node-app

      - name: Health Check
        run: |
          sleep 5
          curl -f http://localhost:8080 || (echo "Health check failed, rolling back" && docker stop hello-node-staging && exit 1)
